# Generated by Django 2.0.2 on 2018-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='keyword',
        ),
        migrations.AddField(
            model_name='info',
            name='keywords',
            field=models.ManyToManyField(to='detector.Keyword'),
        ),
    ]
