# Generated by Django 2.0.2 on 2018-02-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detector', '0002_auto_20180227_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='user',
        ),
        migrations.AddField(
            model_name='info',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.Keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
