# Generated by Django 2.0.2 on 2018-02-27 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_auto_20180227_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
