# Generated by Django 2.0.2 on 2018-02-27 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_auto_20180227_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(default='정부 규제', to=settings.AUTH_USER_MODEL),
        ),
    ]
