# Generated by Django 2.0.2 on 2018-02-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_auto_20180227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(default='정부 규제', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
