# Generated by Django 2.0.2 on 2018-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_auto_20180227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(default=['정부 규제', '비트코인규제'], max_length=50),
        ),
    ]
