# Generated by Django 2.0.2 on 2018-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_auto_20180227_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(default='정부 규제', max_length=50),
        ),
    ]
